baseURL = "https://www.duma.website/"
languageCode = "en-us"
title = "Duma's website"
theme = ["duma_template"]
paginate = 5
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true