name = "duma_template"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE"
description = "The template for my website"
homepage = "http://www.duma.website"

[author]
  name = "Duma"
  homepage = "http://www.duma.website"
